name: Build and Release Sysext Package

run-name: >
  Publish ${GITHUB_REF_NAME}

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build SquashFS
        run: |
          ./build.sh

      - name: Extract Timestamp
        id: version
        run: |
          source output/*.manifest
          echo "BUILD_TIME=${BUILD_TIME}" >> $GITHUB_OUTPUT

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          path: output/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Build Release Metadata
        id: metadata
        run: |
          JSON="{\"version\":\"${GITHUB_REF_NAME#v}\",\"date\":\"$(date +%FT%T)\",\"package_versions\":{"
          for i in $(find artifacts -name *.manifest); do
            source $i
            JSON="${JSON}\"${VERSION_CODENAME}_${ARCH}\":\"${PACKAGE_VERSION}\","
          done
          JSON="${JSON%,}}}"
          echo -n $JSON > release.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            artifacts/**/*.squashfs
            artifacts/**/*.manifest
            release.json
          token: ${{ secrets.RELEASE_TOKEN }}
          overwrite_files: true
